"""init

Revision ID: 18086e6f95b1
Revises: 
Create Date: 2017-08-02 21:17:14.718699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18086e6f95b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('tire_pressure', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=16), nullable=True),
    sa.Column('model', sa.String(length=16), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=63), nullable=True),
    sa.Column('current_login_ip', sa.String(length=63), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('lastSync', sa.DateTime(), nullable=True),
    sa.Column('vehicleUse', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vehicleUse'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('data',
    sa.Column('logger_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('accel_x', sa.Float(), nullable=True),
    sa.Column('accel_y', sa.Float(), nullable=True),
    sa.Column('accel_z', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['logger_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_timestamp'), 'data', ['timestamp'], unique=False)
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_index(op.f('ix_data_timestamp'), table_name='data')
    op.drop_table('data')
    op.drop_table('users')
    op.drop_table('vehicles')
    op.drop_table('roles')
    # ### end Alembic commands ###
